// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQHO8gSJC6ghao-T7O7xqxa9xhvfjS_jE',
    appId: '1:1010328611770:web:62ff28cf99f4c16e834b83',
    messagingSenderId: '1010328611770',
    projectId: 'techmates-982ca',
    authDomain: 'techmates-982ca.firebaseapp.com',
    storageBucket: 'techmates-982ca.firebasestorage.app',
    measurementId: 'G-C4C69W2BV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsn4pY0TeGegqeNiMOqcSDW1EO0MJVdVo',
    appId: '1:1010328611770:android:26b7f65204a26838834b83',
    messagingSenderId: '1010328611770',
    projectId: 'techmates-982ca',
    storageBucket: 'techmates-982ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL89dVIWebojlE5OrX90pLp0P2vDT3RSs',
    appId: '1:1010328611770:ios:fd77fa76d8a13b6b834b83',
    messagingSenderId: '1010328611770',
    projectId: 'techmates-982ca',
    storageBucket: 'techmates-982ca.firebasestorage.app',
    iosBundleId: 'com.example.techmates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL89dVIWebojlE5OrX90pLp0P2vDT3RSs',
    appId: '1:1010328611770:ios:fd77fa76d8a13b6b834b83',
    messagingSenderId: '1010328611770',
    projectId: 'techmates-982ca',
    storageBucket: 'techmates-982ca.firebasestorage.app',
    iosBundleId: 'com.example.techmates',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQHO8gSJC6ghao-T7O7xqxa9xhvfjS_jE',
    appId: '1:1010328611770:web:842dd578c8f93083834b83',
    messagingSenderId: '1010328611770',
    projectId: 'techmates-982ca',
    authDomain: 'techmates-982ca.firebaseapp.com',
    storageBucket: 'techmates-982ca.firebasestorage.app',
    measurementId: 'G-PCLLNE69RS',
  );
}
